### PR TITLE
Change bcrypt dependency for bcryptjs, native js module

### PR DESCRIPTION
**Pull request by julianitor**
Hi Carlos,

I thought it might be OK if the `bcrypt` dependency could be swaped for a js native dependency ported from the first one.

I've faced some problems with `bcrypt` at the time of generating binaries on my Ubuntu, and I've found out that it still has some issues compiling on Win64. Moreover, I've been recently working in projects where compiled dependencies have been a pain in the ass, so I think the less compiled libs we have, the happier we are.

I think [bcryptjs](https://www.npmjs.com/package/bcryptjs) can fit for this base app.

The API of `bcryptjs` and `bcrypt` are exactly the same. I've made the swap in my fork and everything behaves as expected.

Anyway, sorry if I'm missing something and we should use `bcrypt` for a good reason.

Also include pm2 as daemon (instead of nodemon / forever), and as a tool for further deployments and app monitoring.

Regards!

### CODE REVIEW

**Comment by acontreras89** [comment]
I think we should discuss this a bit further. What are the performance and security implications of this change? As soon as I wrote both library names on google, I started seeing mixed opinions on the subject (like [this post](http://stackoverflow.com/questions/22801593/security-differences-with-bcrypt-node-js-modules) or [this one](https://groups.google.com/forum/#!topic/node-red/V7_aFjtpEVE))

**Comment by julianitor** [comment]
Hi,

I've changed this lib in my fork because it was the quickest fix that worked for me. I didn't enjoy facing troubles with deps on the first `npm i`.

Of course, in terms of performance, the non-js lib is better. However, I don't know if we are going to deploy apps in raspberry... I assumed it's going to be a 512MB droplet in the works case. I haven't noticed the difference in this scenario yet.

On security concerns: maybe an attacker has a better deal trying to break or bypass the JS lib than the C++ one, or maybe not. As far as I know, this hasn't happened yet.

There's a way more crypto libs for node-js that could be chosen, but I picked this one because is a JS implementation with the same API than `bcrypt`, which was already implemented in this app.

Your comments are appreciated! The only thing I miss is an alternative solution though. Unless the alternative solution was leaving `bcrypt` as it is, which is nice too!

**Comment by acontreras89** [comment]
Sorry if my comment felt like a rant :sweat_smile: I don't have a better solution for this problem. 
I just wanted to make sure no one merges this before we're certain what the right approach is.

Performance-wise, `bcryptjs` is around 2.7 times slower than its compiled counterpart (as seen in their repo.) Again, I don't know if this should be one of our concerns.

**Comment by julianitor** [comment]
Not at all! I didn't mean to be rude with my answer either.

Any contribution or question pointing to an improvement is appreciated.

**Comment by acontreras89** [comment]
:ship: !

**Pull request merged**
